CREATE TABLE payment_sbus_message (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id      VARCHAR(64)  NOT NULL,
    correlation_id  VARCHAR(64),
    causation_id    VARCHAR(64),
    idempotency_key VARCHAR(128),
    simulation_id   VARCHAR(64),
    status          VARCHAR(32)  NOT NULL,
    payload         JSONB        NOT NULL,
    error_code      VARCHAR(64),
    error_message   TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE payment_sbus_message
    ADD CONSTRAINT uq_payment_sbus_message_request_id UNIQUE (request_id);

CREATE INDEX idx_payment_sbus_message_simulation_id ON payment_sbus_message (simulation_id);
CREATE INDEX idx_payment_sbus_message_idempotency_key ON payment_sbus_message (idempotency_key);
