CREATE TABLE idempotency_record (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_id       VARCHAR(64)  NOT NULL,
    status           VARCHAR(32)  NOT NULL,
    response_payload JSONB,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE idempotency_record
    ADD CONSTRAINT uq_idempotency_record_key UNIQUE (idempotency_key);
